Repository Nonagajyeo/BanThing-docs, pull requests merged in 2025-09, with the labels that each got.

#9 Docs: 회의록 템플릿 마크다운 스타일 수정 및 신규 회의록 추가 (#8)
  meeting-notes/.gitkeep
  meeting-notes/2025-09-05.md
  meeting-notes/2025-09-08.md
  meeting-notes/meeting_notes_template.md
Labels: documentation

#11 Docs: Git 워크플로우 문서 업데이트 및 팀 규칙 추가 (#10)
  rules/workflow.md
Labels: documentation

#16 docs: 프로젝트 개요 문서 추가 (#15)
  planning/overview.md
Labels: documentation

#26 Docs: 불필요한 문서 제거 및 신규 회의록 추가 (#21)
  meeting-notes/2025-09-09.md
  planning/hande_team_roles.md
  planning/moa-life-project-overview-and-feature.md
  planning/moa_platform_overview.md
  retrospective-notes/.gitkeep
  retrospective-notes/Kanggwanju/.gitkeep
  retrospective-notes/hsp64/.gitkeep
  retrospective-notes/minee0505/.gitkeep
  retrospective-notes/retrospective_notes_template.md
  retrospective-notes/rhehdgus8831/.gitkeep
  retrospective-notes/songkey06/.gitkeep
Labels: documentation

#24 docs:userFlow 수정 및 비즈니스로직 변경 #20
  user-flow/.gitkeep
  user-flow/userFlow.md
Labels: documentation

#27 docs: 요구사항 명세서 수정 (#18)
  requirements/requirements.md
  trouble-shooting/.gitkeep
Labels: documentation

#29 Docs: 반띵 플랫폼 컬러 가이드 신규 작성 (#28)
  assets/design/platform-color-guide.md
Labels: documentation

#32 [Docs]: 반띵 서비스 비즈니스 로직 명세서 추가 #30
  requirements/businessLogic.md
Labels: documentation

#41 docs: 법적 리스크 검토 문서 초안 추가 (#40)
  requirements/legalRisks.md
Labels: documentation

#46 docs: 논리 ERD 명세서 및 관련 이미지 추가 (#45)
  architecture/Logical_ERD.md
  assets/img/erd/Logical-ERD-20250910.png
Labels: documentation

#68 Docs: 2025-09-15 회의록 신규 작성 #67
  meeting-notes/2025-09-15.md
Labels: documentation

#69 Docs: 카카오 SSO API 명세서 업데이트 (#66)
  architecture/api/kakao-sso-api-spec.md
Labels: documentation

#72 Docs: 2025-09-16 회의록 신규 작성 #71
  meeting-notes/2025-09-16.md
Labels: documentation

#74 [Docs] 2025-09-17 회의록 신규 작성 #73
  meeting-notes/2025-09-17.md
  meeting-notes/2025-09-18.md
Labels: documentation

#81 Docs: 서비스 이용약관 및 개인정보 처리방침 초기 문서 추가 (#80)
  policies/privacyPolicy.md
  policies/termsOfService.md
Labels: documentation

#83 docs: 모임 상태 관리 스케줄러 명세서 추가 (#82)
  architecture/scheduler-spec.md
Labels: documentation

#91 [Docs] 클론 및 환경설정 가이드, API 설정 가이드 문서 구조 개선 및 표준화 #90
  guides/API_SETUP_GOOGLE_GEMINI.md
  guides/API_SETUP_JWT.md
  guides/API_SETUP_KAKAO_MAP.md
  guides/API_SETUP_KAKAO_OAUTH.md
  guides/SETUP_GUIDE.md
Labels: documentation

#84 docs: 와이어프레임 문서 피드백 모달 내용 추가 및 이미지 삽입 (#79)
  assets/img/wireframe/v2.0.0/wireframe-meeting-detail-feedback-20250922.png
  wireframe/wireframe-meeting-detail.md
Labels: documentation, enhancement

#93 [Docs]: API 명세서, 트러블슈팅 등 주요 문서 5건 추가 및 업데이트(#92, #89, #88, #86, #85)
  architecture/api/general-api-spec.md
  architecture/api/kakao-map-sdk-spec.md
  planning/overview.md
  planning/research.md
  requirements/legalRisks.md
  trouble-shooting/rhehdgus8831/N+1_TroubleShooting.md
  trouble-shooting/rhehdgus8831/ProvideId_TroubleShooting.md
  trouble-shooting/rhehdgus8831/meeting_participants_TroubleShooting.md
Labels: documentation, enhancement, refactor

#96 [Docs] 프로젝트 구조 가이드 문서 관리 체계 완성 및 상호 참조 추가 #95
  guides/SETUP_GUIDE.md
  guides/STRUCTURE_GUIDE.md
Labels: documentation

#99 [Docs] AI 챗봇 API 명세서 v2.0.0 전면 개편 #98
  architecture/api/ai-chatbot-api-spec.md
Labels: documentation

#103 docs: 와이어프레임 문서 링크 및 포맷 수정 (#100)
  planning/roadmap.md
  requirements/requirements.md
  wireframe/wireframe-main-page.md
  wireframe/wireframe-meeting-detail.md
  wireframe/wireframe-my-page.md
Labels: documentation, enhancement, refactor

#125 Docs: 기술 스택 문서 업데이트 (#124)
  tech/tech-stack.md
Labels: documentation
